---
- name: Configure NGINX Load Balancer
  hosts: all
  become: true
  gather_facts: yes

  vars:
    app_server_ips: "{{ lookup('env', 'APP_SERVER_IPS').split(',') }}"

  tasks:
    - name: Install NGINX
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Configure NGINX for load balancing
      ansible.builtin.copy:
        dest: /etc/nginx/nginx.conf
        content: |
          user nginx;
          worker_processes auto;

          events {
              worker_connections 1024;
          }

          http {
              upstream flask_app {
              {% for ip in app_server_ips %}
                  server {{ ip }}:5000;
              {% endfor %}
              }

              server {
                  listen 80;
                  location / {
                      proxy_pass http://flask_app;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  }
              }
          }
        owner: root
        group: root
        mode: "0644"

    - name: Test NGINX configuration
      ansible.builtin.command:
        cmd: nginx -t

    - name: Restart NGINX
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: true
