---
- name: Setup Docker, Terraform v1.10.0, and AWS CLI on Amazon Linux 2023
  hosts: all
  become: true
  gather_facts: yes

  vars:
    db_endpoint_full: "{{ lookup('env', 'DB_ENDPOINT') }}"
    db_endpoint: "{{ db_endpoint_full.split(':')[0] }}"
    db_name: "test_db"

  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest

    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to the docker group
      user:
        name: ec2-user
        groups: docker
        append: true

    - name: Run the Docker container
      community.docker.docker_container:
        name: flask-mysql-app
        image: jjorozco20/flask-mysql-app:latest
        state: started
        published_ports:
          - "5000:5000"
        env:
          MYSQL_HOST: "{{ db_endpoint }}"
          MYSQL_DB: "{{ db_name }}"
