---
- name: Setup Docker on Amazon Linux 2023
  hosts: all
  become: true
  gather_facts: yes

  vars:
    db_endpoint_full: "{{ lookup('env', 'DB_ENDPOINT') }}"
    db_endpoint: "{{ db_endpoint_full.split(':')[0] }}"

  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest

    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to the docker group
      user:
        name: ec2-user
        groups: docker
        append: true

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Create Docker Compose file
      copy:
        dest: /home/ec2-user/docker-compose.yml
        content: |
          ---
          services:
            app:
              image: jjorozco20/flask-mysql-app
              ports:
                - "5000:5000"  # Maps port 5000 on the host to port 5000 in the container
              environment:
                MYSQL_HOST: "{{ db_endpoint }}"
    - name: Run the Docker container
      shell: |
        docker run -d \
          -e MYSQL_HOST={{ db_endpoint }} \
          -p 5000:5000 \
          jjorozco20/flask-mysql-app:latest
      register: docker_run
      failed_when: docker_run.rc != 0
      changed_when: true

    # - name: Run Docker Compose to start the app
    #   command: docker-compose -f /home/ec2-user/docker-compose.yml up -d
    #   args:
    #     chdir: /home/ec2-user
