---
- name: Setup Docker, Terraform v1.10.0, and AWS CLI on Amazon Linux 2023
  hosts: all
  become: true
  gather_facts: yes

  vars:
    db_endpoint_full: "{{ lookup('env', 'DB_ENDPOINT') }}"
    db_endpoint: "{{ db_endpoint_full.split(':')[0] }}"
    terraform_version: "1.10.0"

  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest

    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to the docker group
      user:
        name: ec2-user
        groups: docker
        append: true

    - name: Download Terraform
      get_url:
        url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        dest: /tmp/terraform.zip

    - name: Unzip Terraform binary
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Ensure Terraform is executable
      file:
        path: /usr/local/bin/terraform
        mode: '0755'

    - name: Verify Terraform installation
      shell: "terraform version"
      register: terraform_version_output

    - name: Install AWS CLI
      package:
        name: aws-cli
        state: present

    - name: Run the Docker container
      community.docker.docker_container:
        name: flask-mysql-app
        image: jjorozco20/flask-mysql-app:latest
        state: started
        published_ports:
          - "5000:5000"
        env:
          MYSQL_HOST: "{{ db_endpoint }}"
