name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ./flask-app  # Specify if your code is in a subdirectory

    # Step 2: Install Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest

    # Step 3: Navigate to Terraform Directory
    - name: Change Directory to Terraform
      run: cd terraform

    # Step 4: Initialize Terraform
    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    # Step 5: Plan Terraform Changes
    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan

    # Step 6: Wait for Manual Approval
    - name: Await Approval
      uses: hmarr/auto-approve-action@v2
      with:
        require-approval: true

    # Step 7: Apply Terraform Changes
    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve
